packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  "@prisma/client": true
  "@prisma/engines": true
  "@sentry-internal/node-native-stacktrace": false
  "better-sqlite3": true
  "cpu-features": false
  "esbuild": false
  "prisma": true
  "sharp": false
  "ssh2": false
